apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-datasources
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://github.com/dein-user/argo-manifests.git
    path: lgtm-stack-demo/datasources
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true