apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
type: Opaque
data:
  loki-datasource.yaml: |
    YXBpVmVyc2lvbjogMQpkYXRhc291cmNlczogCi0gbmFtZTogTG9raQogIHR5cGU6IGxva2kKICBhY2Nlc3M6IHByb3h5CiAgdXJsOiBodHRwOi8vbG9raS5tb25pdG9yaW5nLnN2Yy5jbHVzdGVyLmxvY2FsOjMxMDAKICBpc0RlZmF1bHQ6IGZhbHNlCiAganNvbkRhdGE6CiAgICBodHRwSGVhZGVyTmFtZTE6ICJYLVNjb3BlLU9yZ0lEIgoKICBzZWN1cmVKc29uRGF0YToKICAgIGh0dHBIZWFkZXJWYWx1ZTE6ICJhbm9ueW1vdXM=