apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-mimir
  namespace: monitoring
  labels:
    grafana_datasource: "1"
type: Opaque
data:
  mimir-datasource.yaml: |
    YXBpVmVyc2lvbjogMQpkYXRhc291cmNlczogCi0gbmFtZTogTWltaXIKICB0eXBlOiBwcm9tZXRoZXVzCiAgYWNjZXNzOiBwcm94eQogIHVybDogImh0dHA6Ly9taW1pci5tb25pdG9yaW5nLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDkvcHJvbWV0aGV1cyIKICBpc0RlZmF1bHQ6IGZhbHNlCiAganNvbkRhdGE6CiAgICB0aW1lSW50ZXJ2YWw6ICI0MHMiCiAgICBodHRwSGVhZGVyTmFtZTE6ICJYLVNjb3BlLU9yZ0lEIgoKICBzZWN1cmVKc29uRGF0YToKICAgIGh0dHBIZWFkZXJWYWx1ZTE6ICJhbm9ueW1vdXM=