apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-tempo
  namespace: monitoring
  labels:
    grafana_datasource: "1"
type: Opaque
data:
  tempo-datasource.yaml: |
    YXBpVmVyc2lvbjogMQpkYXRhc291cmNlczogCi0gbmFtZTogVGVtcG8KICB0eXBlOiB0ZW1wbwogIGFjY2VzczogcHJveHkKICB1cmw6IGh0dHA6Ly90ZW1wby5tb25pdG9yaW5nLnN2Yy5jbHVzdGVyLmxvY2FsOjMxMDAKICBpc0RlZmF1bHQ6IGZhbHNl