apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: loki-helm
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.29.0
    helm:
      valuesObject:
          deploymentMode: SingleBinary
          loki:
            useTestSchema: true
            chunksCache:
              enabled: false
            storage:
              type: filesystem
              filesystem:
              directory: /var/loki/chunks
              bucketNames:
              chunks: loki-chunks
          singleBinary:
              replicas: 1
          backend:
              replicas: 0
          read:
              replicas: 0
          write:
              replicas: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true