apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lgtm-stack-demo
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: nginx-test
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '*'